version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ai-testing-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: ai-testing-frontend
    ports:
      - "3000:3000"
    volumes:
     - ./frontend:/app
    stdin_open: true
    tty: true