#version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ai-testing-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - ENCRYPTION_KEY=mgkHkjQ0sXO9JNq8aJB0xtar97shnF3tA0qpxHx0sCE=
    platform: linux/amd64

  frontend:
    build: ./frontend
    container_name: ai-testing-frontend
    ports:
      - "4200:4200"
    volumes:
     - ./frontend:/app
    stdin_open: true
    tty: true